//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class bd04_common_code
    {
        public string bcc_id { get; set; }
        public int bcc_id2 { get; set; }
        public string bcc_name { get; set; }
        public string bcc_type { get; set; }
        public string bcc_memo { get; set; }
        public System.DateTime make_date { get; set; }
    }
}
