//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SMSEntities : DbContext
    {
        public SMSEntities()
            : base("name=SMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bd01_org> bd01_org { get; set; }
        public virtual DbSet<bd02_dept> bd02_dept { get; set; }
        public virtual DbSet<bd03_user> bd03_user { get; set; }
        public virtual DbSet<sm01_soft_keep_main> sm01_soft_keep_main { get; set; }
        public virtual DbSet<sm02_soft_keep_detail> sm02_soft_keep_detail { get; set; }
        public virtual DbSet<bd04_common_code> bd04_common_code { get; set; }
    
        public virtual ObjectResult<SM01_GetUsableDeptByYearOrg_Result> SM01_GetUsableDeptByYearOrg(string year, string org)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var orgParameter = org != null ?
                new ObjectParameter("org", org) :
                new ObjectParameter("org", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SM01_GetUsableDeptByYearOrg_Result>("SM01_GetUsableDeptByYearOrg", yearParameter, orgParameter);
        }
    
        public virtual ObjectResult<SM01_GetUsableOrg_Result> SM01_GetUsableOrg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SM01_GetUsableOrg_Result>("SM01_GetUsableOrg");
        }
    
        public virtual ObjectResult<SM01_GetUsableUserByYearOrgDept_Result> SM01_GetUsableUserByYearOrgDept(string year, string org, string dept)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var orgParameter = org != null ?
                new ObjectParameter("org", org) :
                new ObjectParameter("org", typeof(string));
    
            var deptParameter = dept != null ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SM01_GetUsableUserByYearOrgDept_Result>("SM01_GetUsableUserByYearOrgDept", yearParameter, orgParameter, deptParameter);
        }
    }
}
